# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c08f42daa6f081347fd0f0844aacaf4cb080136f21ca136cc2ec2e9e75161c1152e880b5778fd4733ee76c47a4ec6656d32ca6afa22a77767782a65ddeacbeb9

test:
  secret_key_base: 64f57a6aaef05043a80da9d0324cf38adabcd61a02dd5032ea598fbc26db59219607dd41381d31bf2c25c7afb4ee5a5b0836a35fdb961a0aa0467ffb6b11aca8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
